### PR TITLE
Just some small changes 

### PR DESCRIPTION
**Pull request by zero-impact**
I haven't merged in a while. Just a few small changes

### CODE REVIEW

**Comment by dilevin** [comment]
please fix the windows build error.

**Comment by zero-impact** [comment]
It looks like this is some problem deep in TimeStepperEulerImplicit on Windows.
Specifically it is complaining about a sparse matrix transpose on TimeStepperEulerImplicit.h(115) I think?

Anyways, I assume this is why Example 11 wasn't in the cmake file to start with.. so I will just get rid of it for now and file an issue.

**Comment by dilevin** [comment]
I think its because my newton solver uses Pardiso for this example so it doesn't build on windows. I never implemented a Eigen workaround.

**Comment by zero-impact** [comment]
#16

**Comment by zero-impact** [comment]
There must be an eigen work around because it works on my machine with no pardiso

**Pull request merged**
